### ISSUE TITLE
Difference LinAlg4DataScience and LinAlgBook

### ISSUE THREAD

**Issue by tim-meese** [mikexcohen/LinAlg4DataScience#6]
Hello

Noticed that you wrote two textbooks about linear algebra: 
i. Linear Algebra: Theory, Intuition, Code
ii. Practical Linear Algebra for Data Science

Based on their descriptions, I would assume that book i. has more content than book ii. and that everything that is book ii. is also in book i. 
Is this correct? 

With kind regards
Tim

**Comment by mikexcohen** [comment]
Hi Tim. The two books do overlap, but not entirely. The "theory" book is longer and more focused on concepts, theory, and proofs (though still with an eye on implementations and applications); while the O'Reilly book is more focused on implementations and applications (though still with an eye on proofs). So the question is whether you are looking for a deeper and more thorough dive into linear algebra, or want to get up to speed quickly with applications. I also try to use different examples and exercises across the two books, so the practical work is mostly non-overlapping (with occasional redundancies).

**Comment by tim-meese** [comment]
Dear Mike

Thank you for your quick and clear answer. 

I am interested in bioinformatics and statistics. I noticed that many tools and algorithms rely on linear algebra, so I want to expand my knowledge about it. I have no strong background in mathematics. Which book would you recommend?

**Comment by tim-meese** [comment]
Thank you for the input. I appreciate it.

**Comment by tim-meese** [comment]
Ordered a physical copy of the theory book. Looking forward starting my journey in the linear algebra world.
