### ISSUE TITLE
Ch03.  Excersie-3, Plotly renders empty picture in WSL2

### ISSUE THREAD

**Issue by maxzaikin** [mikexcohen/LinAlg4DataScience#8]
Hi, Mike.

First I want to appreciate your amazing book, reading it I hav learned a lot. 

I would like to report an issue, which I wasn't able to resolve by my self. In my home lab, i have installed Jupyter lab via Windows-11/WSL2-Ubuntu environment as I also practicing with TF and Keras, so maybe this is the issue, but for some reasons code with plotly in ex-3 doesn't render any image. If you could help resolve this problem I would very appreciate you.

Best regards,
Maks.

**Comment by mikexcohen** [comment]
Hi Maks. Unfortunately, Python graphics can be highly IDE-specific. I just tested the code in colab and it works well there. Colab runs ployly version 5.24.1, and matplotlib version 3.8.0.

But my honest advise is to skip that visualization on your computer and run that on colab. It's not critical to the rest of the book, and I'm not sure it's worth your time to spend several hours trying to fix/update/install just for one figure.

**Comment by maxzaikin** [comment]
Dear Mike,

thank you for your reply and advise, which I'm certainly will follow up.

Best regards,
Maks.
